name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug-candidate"]
body:
  - type: markdown
    attributes:
      value: >
        Please check the issues tab to avoid duplicates.
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: "Describe the issue:"
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: "Reproduce the code example:
      description: >
      It can be a github repo, etherscan link, or code snippet.
      placeholder: "contract A {}"
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: "Version:"
      description: What version of slither are you running? Run `slither --version`
      placeholder: 0.8.2
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: >
      Please copy and paste any relevant log output. This 
      will be automatically formatted into code, so no need for backticks.
      render: shell
